#!/bin/bash
outdir="out"
tmc_path="../Heather/solidity/Tmc3.sol"
TC_path="../Heather/examples/expandedScaleFunction0.bahr"
con_exe_path="test/contract_execution/expandedScaleFunction0.js"

rm -rf $outdir
./compile_and_deploy $outdir $tmc_path 1000 "'DKK'" 0 "'DKK'"
./compile_and_deploy $outdir $TC_path
./run_code $outdir $con_exe_path
