#!/bin/bash
outdir="out"
tmc_path="../Daggerc/solidity/Tmc3.sol"
TC_path="../Daggerc/examples/expandedScaleFunction0.bahr"
con_exe_path="test/contract_execution/expandedScaleFunction0.js"

rm -rf $outdir
./compile_and_deploy.pl $outdir $tmc_path 1000 "'DKK'" 0 "'DKK'"
./compile_and_deploy.pl $outdir $TC_path
./run_code.pl $outdir $con_exe_path
