#!/bin/bash
# IPC path is a hardcoded value in Ethereum Wallet GUI, cf.
# http://ethereum.stackexchange.com/questions/4418/how-to-change-to-private-network-in-etherum-wallet/4429
system_platform=$(uname)

if [[ $system_platform == "Linux" ]]
then
    ipcpath="$HOME/.ethereum/geth.ipc"
elif [[ $system_platform == "Darwin" ]]
then
    ipcpath="$HOME/Library/Ethereum/geth.ipc"
else
    echo "The system system platform is not Linux or Darwin, we only support one of these"
    exit 1
fi

own_ip=$(ifconfig | grep inet | grep -i Mask | grep -i cast | awk '{print $2}' | sed 's/addr://')
geth --fast --cache 512 --ipcpath $ipcpath --networkid 42 --port 30301 --rpc --rpcaddr $own_ip --rpcport 30302 --datadir ./.ethereum_testserver_data --jspath ./scripts/ --mine --minerthreads=1 console 2>> ./out/error.log
