#!/bin/bash

rm -f out/contracts.json
echo PMD0

./compile_and_deploy.pl out/ example/Erc20.sol "'DKK'" "'DKK'" 1 1000000
echo PMD1

./compile_and_deploy.pl out/ example/SimpleTransfer.dag
echo PMD2

./run_code.pl out example/SimpleTransfer.js
echo PMD3
