#!/bin/bash

rm -f out/contracts.json
./compile_and_deploy.pl out/ example/Erc20.sol "'DKK'" "'DKK'" 1 1000000
./compile_and_deploy.pl out/ example/SimpleTransfer.dag
./run_code.pl out example/SimpleTransfer.js
