#!/bin/bash

rm -f out/contracts.json
./compile_and_deploy.pl out/ example/Erc20.sol "'CHF'" "'CHF'" 0 20000
./compile_and_deploy.pl out/ example/DataFeed0.sol
./compile_and_deploy.pl out/ example/BettingExample2.dag
./run_code.pl out example/bettingTest.js
