#!/bin/bash
genesis_fn="./testserver_genesis.json"
datadir=".ethereum_testserver_data/"
outdir="out/"
echo "Are you sure you wish to delete any existing block chain data and *ALL PRIVATE KEYS*? Y/N"
read delete
if [ "$delete" == "Y" ]
then
    rm -r $datadir
    echo "Creating new genesis block from $genesis_fn:"
    geth --datadir $datadir init $genesis_fn
    echo "Creating new account:"
    geth account new
    rm -rf $outdir
    mkdir $outdir
fi
